import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import LoginBtn from "@/app/login/LoginBtn";
import {getServerSession} from "next-auth";
import {authOptions} from "@/pages/api/auth/[...nextauth]";
import LogoutBtn from "@/app/login/LogoutBtn";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({children}) {
  const loginSession = await getServerSession(authOptions);
  return (
      <html lang="en">
      <body className={inter.className}>
      <div className="navbar">
        <Link href="/" className="logo">갤럭시</Link>
        <Link href="/list">List</Link>
        {loginSession?  <Link href="/write">Write</Link> : null}
        {loginSession ? <span>{loginSession.user.name}<LogoutBtn/></span> : <LoginBtn />}
      </div>
      {children}</body>
      </html>
  );
}
